// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendTasksToFile(arg1) {
  return window['go']['main']['App']['AppendTasksToFile'](arg1);
}

export function ClearTaskList() {
  return window['go']['main']['App']['ClearTaskList']();
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function LoadFile() {
  return window['go']['main']['App']['LoadFile']();
}

export function SortTasks() {
  return window['go']['main']['App']['SortTasks']();
}

export function UpdateTaskStatus(arg1) {
  return window['go']['main']['App']['UpdateTaskStatus'](arg1);
}
