// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendTasksToFile(arg1:string):Promise<void>;

export function ClearTaskList():Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function LoadFile():Promise<string>;

export function SortTasks():Promise<void>;

export function UpdateTaskStatus(arg1:string):Promise<void>;
